# Generated by Django 3.1 on 2020-09-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='state',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
