# Generated by Django 3.1 on 2020-09-19 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 13, 5, 43, 274423)),
        ),
    ]
