# Generated by Django 3.1 on 2020-09-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_equipment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
