# Generated by Django 3.1 on 2020-09-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='due',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
