# Generated by Django 3.1 on 2020-09-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_auto_20200905_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='borrower',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
