# Generated by Django 3.1 on 2020-09-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_equipment_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
