# Generated by Django 3.1 on 2020-09-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_auto_20200903_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='state',
        ),
    ]
