# Generated by Django 3.1 on 2020-09-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_auto_20200903_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='bunrui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
