# Generated by Django 3.1 on 2020-09-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_bunrui'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='state',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
