# Generated by Django 3.1 on 2020-09-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_equipment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='borrower',
            field=models.TextField(blank=True, null=True),
        ),
    ]
