# Generated by Django 3.1 on 2020-09-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0011_equipment_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='bunrui',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipments.bunrui'),
            preserve_default=False,
        ),
    ]
