# Generated by Django 3.1 on 2020-09-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0012_equipment_bunrui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='bunrui',
        ),
    ]
