# Generated by Django 3.1 on 2020-09-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0013_remove_equipment_bunrui'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bunrui',
        ),
    ]
