# Generated by Django 3.1 on 2020-09-04 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bunrui', '0001_initial'),
        ('equipments', '0014_delete_bunrui'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='bunruiname',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bunrui.bunrui'),
        ),
    ]
