# Generated by Django 3.1 on 2020-09-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0016_auto_20200904_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunruiname',
            name='bunruiid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
